### ISSUE TITLE
Exception not caught

### ISSUE THREAD

**Issue by boexler** [jeromerg/NAsync#1]
I want to use your library to catch `Exceptions` in `Tasks` or methods which will use `async/await`.
Unfortunately the `Exception` is not caught.

```cs
public class TaskExtensionsTests
    {
        [Fact]
        public async Task CatchReturnStatusTest()
        {
            try
            {
                await GetException().Then(() =>
                {

                }).Catch<Exception>(exception =>
                {

                });
            }
            catch (Exception e)
            {
                
            }
        }

        private Task GetException() => throw new NotImplementedException();
    }
```

![image](https://user-images.githubusercontent.com/17551597/123238509-d2d5fe80-d4de-11eb-976e-dfb5bf2e0227.png)

**Comment by boexler** [comment]
Found my mistake.. 🤦‍♂️

**Comment by jeromerg** [comment]
Glad to see that you have solved the issue. This Library was develop many years ago as a workaround to missing `async`/`await` in legacy C# Versions... You should try to use `async`/`await` instead if you can / are allowed, as it offers the same possibilities to handle async processings and more (better support for try/catch, loops...)

**Comment by boexler** [comment]
Thanks for the feedback! Unfortunately, I haven't found a clean way to catch exceptions cleanly without the hassle of using a `TryCatch` block.

I use a `ReturnStatus` class in my code with which I perform all error handling and logging.

The combination with your extension methods seems quite elegant to me!
You are welcome to correct me and show me a better way.

```cs
public static Task<HtReturnStatus<T>> ToHtReturnStatus<T>([NotNull] this Task<T> first, [CanBeNull] TaskScheduler taskScheduler = null)
      => first.Then(HtReturnStatus.Success).Catch<HtReturnStatus<T>, Exception>(exception => HtReturnStatus.Failed<T>(exception), taskScheduler);
```

```cs
[Fact]
public async Task ToHtReturnStatus_ReturnValueTest()
{
	var result = await ThrowArgumentNullWithReturnValue().ToHtReturnStatus();
	result.ShouldHaveFailed(HtErrorCode.EXCEPTION_ArgumentNull);

	var result2 = await SuccessTaskWithReturnValue().ToHtReturnStatus();
	result2.ShouldHaveSucceeded();
	result2.Result.Should().Be(123);
}

private async Task<int> SuccessTaskWithReturnValue()
{
	await Task.Delay(1);
	return 123;
}

private async Task<int> ThrowArgumentNullWithReturnValue()
{
	await Task.Delay(1);
	throw new ArgumentNullException();
}
```
